theme: primer
title: 0xBrics - An Algorithmic, Multi-collateral Stablecoin Protocol
description: Thie litepaper describes the 0xBrics protocol, a decentralized, algorithmic, multi-collateral stablecoin protocol pegged to the value of the BRICS currency.